// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_categorySlug_postSlug_ from "./routes/[categorySlug]/[postSlug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_categories_index from "./routes/admin/categories/index.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $admin_logout from "./routes/admin/logout.tsx";
import * as $admin_pages_index from "./routes/admin/pages/index.tsx";
import * as $admin_posts_id_edit from "./routes/admin/posts/[id]/edit.tsx";
import * as $admin_posts_index from "./routes/admin/posts/index.tsx";
import * as $admin_posts_new from "./routes/admin/posts/new.tsx";
import * as $api_categories_id_ from "./routes/api/categories/[id].ts";
import * as $api_categories_index from "./routes/api/categories/index.ts";
import * as $api_pages_id_ from "./routes/api/pages/[id].ts";
import * as $api_pages_index from "./routes/api/pages/index.ts";
import * as $api_posts_id_ from "./routes/api/posts/[id].ts";
import * as $api_posts_index from "./routes/api/posts/index.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $category_slug_ from "./routes/category/[slug].tsx";
import * as $index from "./routes/index.tsx";
import * as $page_slug_ from "./routes/page/[slug].tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.ts";
import * as $BlogInteractions from "./islands/BlogInteractions.tsx";
import * as $Editor from "./islands/Editor.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[categorySlug]/[postSlug].tsx": $_categorySlug_postSlug_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/categories/index.tsx": $admin_categories_index,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/admin/logout.tsx": $admin_logout,
    "./routes/admin/pages/index.tsx": $admin_pages_index,
    "./routes/admin/posts/[id]/edit.tsx": $admin_posts_id_edit,
    "./routes/admin/posts/index.tsx": $admin_posts_index,
    "./routes/admin/posts/new.tsx": $admin_posts_new,
    "./routes/api/categories/[id].ts": $api_categories_id_,
    "./routes/api/categories/index.ts": $api_categories_index,
    "./routes/api/pages/[id].ts": $api_pages_id_,
    "./routes/api/pages/index.ts": $api_pages_index,
    "./routes/api/posts/[id].ts": $api_posts_id_,
    "./routes/api/posts/index.ts": $api_posts_index,
    "./routes/api/upload.ts": $api_upload,
    "./routes/category/[slug].tsx": $category_slug_,
    "./routes/index.tsx": $index,
    "./routes/page/[slug].tsx": $page_slug_,
    "./routes/sitemap.xml.ts": $sitemap_xml,
  },
  islands: {
    "./islands/BlogInteractions.tsx": $BlogInteractions,
    "./islands/Editor.tsx": $Editor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
